import js from '@eslint/js';

const NODE_GLOBALS = {
  process: 'readonly',
  console: 'readonly',
  Buffer: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  require: 'readonly',
  module: 'writable',
  exports: 'writable',
  globalThis: 'readonly',
};

const BROWSER_GLOBALS = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  fetch: 'readonly',
  console: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Image: 'readonly',
  atob: 'readonly',
  createImageBitmap: 'readonly',
  PointerEvent: 'readonly',
  performance: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  ResizeObserver: 'readonly',
  EventSource: 'readonly',
  DataTransfer: 'readonly',
  customElements: 'readonly',
  HTMLElement: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  getComputedStyle: 'readonly',
  matchMedia: 'readonly',
  localStorage: 'readonly',
  alert: 'readonly',
  structuredClone: 'readonly',
};

const UNUSED = ['error', {
  caughtErrors: 'none',
  args: 'after-used',
  argsIgnorePattern: '^_',
  varsIgnorePattern: '^_',
}];

export default [
  {
    ignores: [
      'node_modules/**',
      'dist-app/**',
      '_web/**',
      '_work/**',
      '.tools/**',
      'output/**',
      'input/**',
      'fixtures/**',
      'tests/__optimized__/**',
      'coverage/**',
      'core/types.mjs',
      'core/contract.mjs',
      'core/registry.mjs',
      'core/i18n.mjs',
      'core/engine.mjs',
      'addons/gltf/metrics.mjs',
      'addons/gltf/tools.mjs',
      'addons/gltf/rules.mjs',
      'addons/gltf/types.mjs',
      'addons/gltf/index.mjs',
      'optimize2.mjs',
      'server.mjs',
      'assistant.mjs',
      'ui/app.js',
      'ui/i18n.js',
      'ui/viewer/index.js',
      'ui/viewer/viewer.js',
    ],
  },

  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: NODE_GLOBALS,
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': UNUSED,
      'require-atomic-updates': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-irregular-whitespace': ['error', { skipStrings: true, skipTemplates: true, skipComments: true }],
    },
  },

  {
    files: ['desktop/**/*.cjs'],
    languageOptions: { sourceType: 'commonjs', globals: NODE_GLOBALS },
  },

  {
    files: ['ui/**/*.js', 'translations/**/*.js'],
    languageOptions: { sourceType: 'script', globals: BROWSER_GLOBALS },
  },
  {
    files: ['ui/**/*.js'],
    languageOptions: { sourceType: 'module' },
  },

  {
    files: ['tests/**/*.{js,mjs}'],
    languageOptions: {
      globals: { ...NODE_GLOBALS, ...BROWSER_GLOBALS, vi: 'readonly' },
    },
  },
];
